# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravapp', '0002_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='page',
            field=models.IntegerField(default=1, verbose_name=1024),
            preserve_default=False,
        ),
    ]
